
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 23 21:18:23 ART 2022
//----------------------------------------------------

package Principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Estatico = 35;
  public static final int Op_relacional = 17;
  public static final int Op_booleano = 20;
  public static final int If = 6;
  public static final int Void = 33;
  public static final int T_dato = 4;
  public static final int Package = 32;
  public static final int Else = 7;
  public static final int Llave_C = 24;
  public static final int While = 9;
  public static final int Division = 15;
  public static final int Llave_A = 23;
  public static final int Cadena = 5;
  public static final int For = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Private = 36;
  public static final int Linea = 2;
  public static final int Op_atribucion = 18;
  public static final int Corchete_C = 26;
  public static final int Do = 8;
  public static final int ERROR = 31;
  public static final int Corchete_A = 25;
  public static final int Op_logico = 16;
  public static final int Public = 34;
  public static final int Punto_Coma = 28;
  public static final int Parentesis_C = 22;
  public static final int Identificador = 29;
  public static final int Parentesis_A = 21;
  public static final int Resta = 13;
  public static final int Multiplicacion = 14;
  public static final int Op_incremento = 19;
  public static final int Numero = 30;
  public static final int Suma = 12;
  public static final int Main = 27;
  public static final int Igual = 11;
  public static final int Comillas = 3;
}

